data-source/external: Omit query attribute map elements with null values
Reference: https://github.com/hashicorp/terraform-provider-external/pull/194
Reference: https://github.com/hashicorp/terraform-provider-external/issues/208

The migration to terraform-plugin-framework exposes map values wholly and v2.3.0 handled that transition properly. However, v2.3.1 introduced a subtle change where `query` attribute map elements with null values are now sent with an empty string value, rather than being omitted like previously. Since certain receiving `program` may be dependent on the nuance of `query` values, null element values should continue to omit the element entirely to prevent the introduction of a breaking change.

Previously before logic update:

```
=== RUN   TestDataSource_Query_NullElementValue
    data_source_test.go:367: Step 1/1 error: Error running pre-apply refresh: exit status 1

        Error: External Program Execution Failed

          with data.external.test,
          on terraform_plugin_test.tf line 3, in data "external" "test":
           3:                             program = ["/Users/bflad/go/bin/tf-acc-external-data-source"]

        The data source received an unexpected error while attempting to execute the
        program.

        Program: /Users/bflad/go/bin/tf-acc-external-data-source
        Error Message: I was asked to fail

        State: exit status 1
--- FAIL: TestDataSource_Query_NullElementValue (0.26s)
```